name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - "**"
    tags-ignore:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - run: pip install -r requirements.txt
    - run: make lint
    - run: make test
    - name: pytest-coverage-commentator
      uses: coroo/pytest-coverage-commentator@v1.0.2
      with:
        pytest-coverage: pytest-coverage.txt
